// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  roomId: __t.u64().primaryKey().name("room_id"),
  round: __t.u32(),
  phase: __t.string(),
  promptId: __t.string().name("prompt_id"),
  roundStartedAt: __t.timestamp().name("round_started_at"),
  phaseEndsAt: __t.timestamp().name("phase_ends_at"),
  answer: __t.string(),
  usedPrompts: __t.string().name("used_prompts"),
});
