// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  seatId: __t.u64().primaryKey().name("seat_id"),
  roomId: __t.u64().name("room_id"),
  identity: __t.identity(),
  played: __t.bool(),
  locked: __t.bool(),
  cardGlyph: __t.string().name("card_glyph"),
  cardEncoding: __t.string().name("card_encoding"),
  cardValue: __t.u32().name("card_value"),
  cardName: __t.string().name("card_name"),
  cardRarity: __t.string().name("card_rarity"),
  wasCorrect: __t.bool().name("was_correct"),
  lastResult: __t.string().name("last_result"),
  score: __t.u32(),
  streak: __t.u8(),
  correct: __t.u32(),
  answered: __t.u32(),
  outRound: __t.u32().name("out_round"),
  place: __t.u8(),
  ratingBefore: __t.u32().name("rating_before"),
  ratingAfter: __t.u32().name("rating_after"),
});
