// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  seatId: __t.u64().name("seat_id"),
  roomId: __t.u64().name("room_id"),
  cardId: __t.string().name("card_id"),
  encoding: __t.string(),
  glyph: __t.string(),
  value: __t.u32(),
  name: __t.string(),
  flavor: __t.string(),
  rarity: __t.string(),
});
