// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  name: __t.string(),
  online: __t.bool(),
  registered: __t.bool(),
  rating: __t.u32(),
  matches: __t.u32(),
  wins: __t.u32(),
  correctAnswers: __t.u32().name("correct_answers"),
  totalAnswers: __t.u32().name("total_answers"),
});
