// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  code: __t.string(),
  name: __t.string(),
  kind: __t.string(),
  visibility: __t.string(),
  capacity: __t.u8(),
  host: __t.identity(),
  phase: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
});
