// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Account = __t.object("Account", {
  identity: __t.identity(),
  email: __t.string(),
  createdAt: __t.timestamp(),
});
export type Account = __Infer<typeof Account>;

export const Call = __t.object("Call", {
  id: __t.u64(),
  roomId: __t.u64(),
  callerSeatId: __t.u64(),
  targetSeatId: __t.u64(),
});
export type Call = __Infer<typeof Call>;

export const Card = __t.object("Card", {
  id: __t.string(),
  encoding: __t.string(),
  glyph: __t.string(),
  value: __t.u32(),
  name: __t.string(),
  flavor: __t.string(),
  rarity: __t.string(),
});
export type Card = __Infer<typeof Card>;

export const GuestLink = __t.object("GuestLink", {
  code: __t.string(),
  guest: __t.identity(),
  createdAt: __t.timestamp(),
});
export type GuestLink = __Infer<typeof GuestLink>;

export const Hand = __t.object("Hand", {
  id: __t.u64(),
  seatId: __t.u64(),
  roomId: __t.u64(),
  cardId: __t.string(),
  encoding: __t.string(),
  glyph: __t.string(),
  value: __t.u32(),
  name: __t.string(),
  flavor: __t.string(),
  rarity: __t.string(),
});
export type Hand = __Infer<typeof Hand>;

export const Match = __t.object("Match", {
  roomId: __t.u64(),
  round: __t.u32(),
  phase: __t.string(),
  promptId: __t.string(),
  roundStartedAt: __t.timestamp(),
  phaseEndsAt: __t.timestamp(),
  answer: __t.string(),
  usedPrompts: __t.string(),
});
export type Match = __Infer<typeof Match>;

export const MatchEvent = __t.object("MatchEvent", {
  id: __t.u64(),
  roomId: __t.u64(),
  round: __t.u32(),
  tone: __t.string(),
  text: __t.string(),
});
export type MatchEvent = __Infer<typeof MatchEvent>;

export const MatchSeat = __t.object("MatchSeat", {
  seatId: __t.u64(),
  roomId: __t.u64(),
  identity: __t.identity(),
  played: __t.bool(),
  locked: __t.bool(),
  cardGlyph: __t.string(),
  cardEncoding: __t.string(),
  cardValue: __t.u32(),
  cardName: __t.string(),
  cardRarity: __t.string(),
  wasCorrect: __t.bool(),
  lastResult: __t.string(),
  score: __t.u32(),
  streak: __t.u8(),
  correct: __t.u32(),
  answered: __t.u32(),
  outRound: __t.u32(),
  place: __t.u8(),
  ratingBefore: __t.u32(),
  ratingAfter: __t.u32(),
});
export type MatchSeat = __Infer<typeof MatchSeat>;

export const MatchTick = __t.object("MatchTick", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  roomId: __t.u64(),
  round: __t.u32(),
  phase: __t.string(),
});
export type MatchTick = __Infer<typeof MatchTick>;

export const MyCalls = __t.object("MyCalls", {});
export type MyCalls = __Infer<typeof MyCalls>;

export const MyHand = __t.object("MyHand", {});
export type MyHand = __Infer<typeof MyHand>;

export const MyPlay = __t.object("MyPlay", {});
export type MyPlay = __Infer<typeof MyPlay>;

export const Play = __t.object("Play", {
  seatId: __t.u64(),
  roomId: __t.u64(),
  handId: __t.u64(),
  playedAt: __t.timestamp(),
});
export type Play = __Infer<typeof Play>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  name: __t.string(),
  online: __t.bool(),
  registered: __t.bool(),
  rating: __t.u32(),
  matches: __t.u32(),
  wins: __t.u32(),
  correctAnswers: __t.u32(),
  totalAnswers: __t.u32(),
});
export type Player = __Infer<typeof Player>;

export const Prompt = __t.object("Prompt", {
  id: __t.string(),
  text: __t.string(),
  answer: __t.string(),
  category: __t.string(),
  difficulty: __t.string(),
  hint: __t.string(),
});
export type Prompt = __Infer<typeof Prompt>;

export const Room = __t.object("Room", {
  id: __t.u64(),
  code: __t.string(),
  name: __t.string(),
  kind: __t.string(),
  visibility: __t.string(),
  capacity: __t.u8(),
  host: __t.identity(),
  phase: __t.string(),
  createdAt: __t.timestamp(),
});
export type Room = __Infer<typeof Room>;

export const Score = __t.object("Score", {
  id: __t.string(),
  name: __t.string(),
  won: __t.bool(),
  rounds: __t.u32(),
  health: __t.u32(),
  score: __t.u32(),
  correctCalls: __t.u32(),
  falseCalls: __t.u32(),
  at: __t.string(),
});
export type Score = __Infer<typeof Score>;

export const Seat = __t.object("Seat", {
  id: __t.u64(),
  roomId: __t.u64(),
  identity: __t.identity(),
  seatIndex: __t.u8(),
  ready: __t.bool(),
  health: __t.u8(),
  eliminated: __t.bool(),
});
export type Seat = __Infer<typeof Seat>;

