// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Account = __t.object("Account", {
  identity: __t.identity(),
  email: __t.string(),
  createdAt: __t.timestamp(),
});
export type Account = __Infer<typeof Account>;

export const Card = __t.object("Card", {
  id: __t.string(),
  encoding: __t.string(),
  glyph: __t.string(),
  value: __t.u32(),
  name: __t.string(),
  flavor: __t.string(),
  rarity: __t.string(),
});
export type Card = __Infer<typeof Card>;

export const GuestLink = __t.object("GuestLink", {
  code: __t.string(),
  guest: __t.identity(),
  createdAt: __t.timestamp(),
});
export type GuestLink = __Infer<typeof GuestLink>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  name: __t.string(),
  online: __t.bool(),
  registered: __t.bool(),
  rating: __t.u32(),
  matches: __t.u32(),
  wins: __t.u32(),
  correctAnswers: __t.u32(),
  totalAnswers: __t.u32(),
});
export type Player = __Infer<typeof Player>;

export const Prompt = __t.object("Prompt", {
  id: __t.string(),
  text: __t.string(),
  answer: __t.string(),
  category: __t.string(),
  difficulty: __t.string(),
  hint: __t.string(),
});
export type Prompt = __Infer<typeof Prompt>;

export const Room = __t.object("Room", {
  id: __t.u64(),
  code: __t.string(),
  name: __t.string(),
  kind: __t.string(),
  visibility: __t.string(),
  capacity: __t.u8(),
  host: __t.identity(),
  phase: __t.string(),
  createdAt: __t.timestamp(),
});
export type Room = __Infer<typeof Room>;

export const Score = __t.object("Score", {
  id: __t.string(),
  name: __t.string(),
  won: __t.bool(),
  rounds: __t.u32(),
  health: __t.u32(),
  score: __t.u32(),
  correctCalls: __t.u32(),
  falseCalls: __t.u32(),
  at: __t.string(),
});
export type Score = __Infer<typeof Score>;

export const Seat = __t.object("Seat", {
  id: __t.u64(),
  roomId: __t.u64(),
  identity: __t.identity(),
  seatIndex: __t.u8(),
  ready: __t.bool(),
  health: __t.u8(),
  eliminated: __t.bool(),
});
export type Seat = __Infer<typeof Seat>;

