// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CreateCustomRoomReducer from "../create_custom_room_reducer";
import DiscardGuestReducer from "../discard_guest_reducer";
import ForfeitReducer from "../forfeit_reducer";
import JoinByCodeReducer from "../join_by_code_reducer";
import JoinRoomReducer from "../join_room_reducer";
import KickReducer from "../kick_reducer";
import LeaveRoomReducer from "../leave_room_reducer";
import LinkGuestClaimReducer from "../link_guest_claim_reducer";
import LinkGuestStartReducer from "../link_guest_start_reducer";
import LockCallsReducer from "../lock_calls_reducer";
import PlayCardReducer from "../play_card_reducer";
import QuickMatchReducer from "../quick_match_reducer";
import RecordScoreReducer from "../record_score_reducer";
import SetCapacityReducer from "../set_capacity_reducer";
import SetNameReducer from "../set_name_reducer";
import SetReadyReducer from "../set_ready_reducer";
import StartMatchReducer from "../start_match_reducer";
import ToggleCallReducer from "../toggle_call_reducer";

export type CreateCustomRoomParams = __Infer<typeof CreateCustomRoomReducer>;
export type DiscardGuestParams = __Infer<typeof DiscardGuestReducer>;
export type ForfeitParams = __Infer<typeof ForfeitReducer>;
export type JoinByCodeParams = __Infer<typeof JoinByCodeReducer>;
export type JoinRoomParams = __Infer<typeof JoinRoomReducer>;
export type KickParams = __Infer<typeof KickReducer>;
export type LeaveRoomParams = __Infer<typeof LeaveRoomReducer>;
export type LinkGuestClaimParams = __Infer<typeof LinkGuestClaimReducer>;
export type LinkGuestStartParams = __Infer<typeof LinkGuestStartReducer>;
export type LockCallsParams = __Infer<typeof LockCallsReducer>;
export type PlayCardParams = __Infer<typeof PlayCardReducer>;
export type QuickMatchParams = __Infer<typeof QuickMatchReducer>;
export type RecordScoreParams = __Infer<typeof RecordScoreReducer>;
export type SetCapacityParams = __Infer<typeof SetCapacityReducer>;
export type SetNameParams = __Infer<typeof SetNameReducer>;
export type SetReadyParams = __Infer<typeof SetReadyReducer>;
export type StartMatchParams = __Infer<typeof StartMatchReducer>;
export type ToggleCallParams = __Infer<typeof ToggleCallReducer>;

